core/urls.py
"""Define URL for Social_book app"""

from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [ 
    path('', views.index, name='index'),
    path('settings', views.settings, name='settings'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('follow', views.follow, name='follow'),
    path('search', views.search, name='search'),
]

social_book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from users.models import FollowCount, Profile
from django.contrib.auth.models import User
from posts.views import Post
from users.views import Profile
from django.urls import reverse
import random


from posts.models import Post
# Create your views here.

@login_required
def index(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = Profile.objects.get(user=user_object)

    #Get all post of user who current user following
    followings = FollowCount.objects.filter(follower=request.user.username)
    posts = []
    for following in followings:
        for temp in Post.objects.filter(user=following.user):
            posts.append(temp)
    
    #Get all user who cureent user are is following.
    all_uers = User.objects.all()
    users_not_followings = []
    for temp in all_uers:
        if FollowCount.objects.filter(follower=request.user.username, 
            user=temp.username) or temp.username == request.user.username:
            #Followed
            pass
        else:
            #Not Follow, add to list to suggestion
            users_not_followings.append(temp)

        #Only get random 5 users to suggest
    random.shuffle(users_not_followings)
    profile_users_not_following_list = []
    if len(users_not_followings) > 5:
        users_not_followings = users_not_followings[:5]

    for temp in users_not_followings:
        profile_users_not_following = Profile.objects.filter(user=temp).first()
        if profile_users_not_following:
            profile_users_not_following_list.append(profile_users_not_following)
    
    context = { 
        'user_profile': user_profile,
        'posts': posts,
        'profile_users_not_following_list': profile_users_not_following_list,
    }
    
    return render(request, 'core/index.html', context)

@login_required
def settings(request):
    user_profile = Profile.objects.get(user=request.user)
    context = {'user_profile': user_profile}
    if request.method == 'POST':
        bio = request.POST['bio']
        location = request.POST['location']
        profileimg = request.FILES.get('image')
        #Process Profileimg
        if profileimg == None:
            #Use default image
            profileimg = user_profile.profileimg
        
        user_profile.profileimg = profileimg
        user_profile.bio = bio
        user_profile.location = location
        user_profile.save()

        context = {'user_profile': user_profile}
        return render(request, 'core/setting.html', context)
    else:
        return render(request, 'core/setting.html', context)

@login_required
def profile(request, pk):
    user_object = User.objects.get(username=pk)
    profile_object = Profile.objects.get(user=user_object)
    posts = Post.objects.filter(user=user_object.username)
    len_posts = len(posts)

    #Compute no_followers and no_followings
    followers = FollowCount.objects.filter(user=pk)
    followings = FollowCount.objects.filter(follower=pk)
    len_followings = len_followers = 0
    if followers.first() != None:
        len_followers = len(followers)
    if followings.first() != None:
        len_followings = len(followings)
    
    #Check Follow or unfollow
    follower = request.user.username
    user = pk

    if FollowCount.objects.filter(follower=follower, user=user):
        button_text = 'Unfollow'
    else:
        button_text = 'Follow'

    context = {
        'user_object': user_object,
        'profile_object': profile_object,
        'posts': posts,
        'len_posts': len_posts,
        'len_followers': len_followers,
        'len_followings': len_followings,
        'button_text': button_text,
    }
    return render(request, 'core/profile.html', context)

@login_required
def follow(request):
    if request.method == 'POST':
        follower = request.POST['follower']
        user = request.POST['user']
        if FollowCount.objects.filter(follower=follower, user=user).first():
            #Unfollow
            delete_follower = FollowCount.objects.filter(follower=follower, user=user).first()
            delete_follower.delete()
        else:
            #follow
            new_follower = FollowCount.objects.create(follower=follower, user=user)
            new_follower.save()
        return redirect(reverse('core:profile', kwargs={'pk':user}))

    return redirect('core:index')

@login_required
def search(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = Profile.objects.get(user=user_object)

    if request.method == 'POST':
        username = request.POST['username']
        #Get all profile of needed users
        user_objects = User.objects.filter(username__icontains = username)
        profile_objects_list = []

        for temp in user_objects:
            profile_object = Profile.objects.filter(user=temp).first()
            if profile_object:
                profile_objects_list.append(profile_object)
    
    context = { 
        'user_profile': user_profile,
        'profile_objects_list': profile_objects_list,
        'len_profile_objects_list': len(profile_objects_list),
        'username': username
    }
    return render(request, 'core/search.html', context)

core/templates/core/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Profile - {{user_object.username}}</title>
   <!-- <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> -->
    
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	
	</div>
	
	<section>
			<div class="feature-photo">
				<figure><img src="{% static 'images/resources/timeline-1.jpg' %}" alt=""></figure>
				<form action="{% url 'core:follow' %}" method="post">
					{% csrf_token %}
					<div class="add-btn">
					<span style="color: white; font-size: 27px; margin-right: 520px;"><b><u><a href="{% url 'core:index' %}">Home</a></u></b></span>
					{% if len_posts > 1 %}
						<span style="color: white; font-size: 27px;"><b>{{len_posts}} posts</b></span>
					{% else %}
						<span style="color: white; font-size: 27px;"><b>{{len_posts}} post</b></span>
					{% endif %}

					{% if len_followings > 1 %}
						<span style="color: white; font-size: 27px;"><b>{{len_followings}} followings</b></span>
					{% else%}
						<span style="color: white; font-size: 27px;"><b>{{len_followings}} following</b></span>
					{% endif %}

					{% if len_followers > 1 %}
						<span style="color: white; font-size: 27px;"><b>{{len_followers}} followers</b></span>
					{% else %}
						<span style="color: white; font-size: 27px;"><b>{{len_followers}} follower</b></span>
					{% endif %}
					<!-- <span style="color: white; font-size: 27px;"><b>5 followings</b></span> -->

					<input type="hidden" value="{{user.username}}" name="follower" />
					<input type="hidden" value="{{user_object.username}}" name="user" />

					{% if user_object.username != user.username %}
						<a data-ripple=""><button type="submit" style="background-color: #ffc0cb; border: #ffc0cb;">{{button_text}}</button></a>
					{% else %}
						<a href="{% url 'core:settings' %}" data-ripple="">Account Settings</a>
					{% endif %}
					</div>
				</form>

				<!-- <form class="edit-phto">
					<i class="fa fa-camera-retro"></i>
					<label class="fileContainer">
						Upload Cover Photo
					<input type="file"/>
					</label>
				</form> -->
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									<img src="{{profile_object.profileimg.url}}" style="height: 250px; width: 100%;" alt="">
									<!-- <form class="edit-phto">
										<i class="fa fa-camera-retro"></i>
										<label class="fileContainer">
											<a href="#account-settings">Upload Profile Photo</a>
										</label>
									</form> -->
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
									  <h5 style="color: black;white-space: nowrap; width: 110px; font-size: 27px;"><b>@{{user_object.username}}</b><!--<i class="fa fa-check-circle" style="color: #48dbfb;" aria-hidden="true"></i>--></h5>
									  <!--<span>Group Admin</span>-->
									</li>
									<!--<li>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Go live!</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Music</a>
										<a class="" href="emporium/index-3.html" title="" data-ripple="">Emporium</a>
										<a class="" href="fitness/index.html" title="" data-ripple="">Health Inspection</a>
										<a class="" href="settings/account-setting.html" title="" data-ripple="">Settings</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Upload</a>
										<a class="" href="time-line.html" title="" data-ripple="">time line</a>
										<a class="" href="timeline-photos.html" title="" data-ripple="">Photos</a>
										<a class="" href="timeline-videos.html" title="" data-ripple="">Videos</a>
										<a class="" href="timeline-friends.html" title="" data-ripple="">Friends</a>
										<a class="" href="timeline-groups.html" title="" data-ripple="">Groups</a>
										<a class="" href="about.html" title="" data-ripple="">about</a>
										<a class="" href="#" title="" data-ripple="">more</a>

									</li>-->
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->
		<section>
			<div class="bio">
				{{profile_object.bio}}
			</div>
		</section>
		
	<section>
		<div class="gap gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row" id="page-contents">
							<div class="col-lg-3">
								<aside class="sidebar static">							
								</aside>
							</div><!-- sidebar -->
							<div class="col-lg-6">
								<div class="central-meta">
									<ul class="photos">
										{% for post in posts %}	
											<li>
												<a class="strip" href="{{post.image.url}}" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
													<img src="{{post.image.url}}" style="height: 250px; width: 300px;" alt=""></a>
											</li>
										{% endfor %}

										<!-- <li>
											<a class="strip" href="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 300px;" alt=""></a>
										</li> -->

										<!-- <li>
											<a class="strip" href="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src="https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" style="height: 250px; width: 300px;" alt=""></a>
										</li> -->
										
										
									</ul>
									<!--<div class="lodmore"><button class="btn-view btn-load-more"></button></div>-->
								</div><!-- photos -->
							</div><!-- centerl meta -->
							<div class="col-lg-3">
								<aside class="sidebar static">
									
								</aside>
							</div><!-- sidebar -->
						</div>	
					</div>
				</div>
			</div>
		</div>	
	</section>

	
	
	<script data-cfasync="false" src="{% static '../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="{% static 'js/main.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>	


</html>

core/templates/core/setting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>Settings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body>
            <div class="container m-auto"> 

                <h1 class="text-2xl leading-none text-gray-900 tracking-tight mt-3"> 
                    <a href="{% url 'core:index' %}">Home</a> / Account Setting for <b>{{user.username}}</b></h1>
                <!-- <ul class="mt-5 -mr-3 flex-nowrap lg:overflow-hidden overflow-x-scroll uk-tab">
                    <li class="uk-active"><a href="#">General</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Notification</a></li>
                    <li><a href="#">Social links</a></li>
                    <li><a href="#">Billing</a></li>
                    <li><a href="#">Security</a></li>
                </ul> -->

                <br>
                <hr>
                <div class="grid lg:grid-cols-3 mt-12 gap-8">
                    <div>
                        <h3 class="text-xl mb-2"> General</h3>
                        <p></p>
                    </div>
                    <div class="bg-white rounded-md lg:shadow-lg shadow col-span-2">
                        <!-- To ensure can post file image set enctype -->
                    <form method="POST" action="{% url 'core:settings' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                       <div class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                           <!-- <div>
                               <label for=""> First name</label>
                               <input type="text" placeholder="Your name.." class="shadow-none bg-gray-100">
                           </div> -->
                           <!-- <div>
                               <label for=""> Last name</label>
                               <input type="text" placeholder="Your name.." class="shadow-none bg-gray-100">
                            </div> -->
                            <!-- <div class="col-span-2">
                                <label for=""> Email</label>
                                <input type="text" placeholder="Your name.." class="shadow-none bg-gray-100">
                            </div> -->
                            
                            <div class="col-span-2">
                                <label for=""> Profile Image</label>
                                <img width="100" height="100" src="{{user_profile.profileimg.url}}" />
                                <input type="file" name="image" rows="3" class="shadow-none bg-gray-100">
                            </div>
                            <div class="col-span-2">
                                <label for="about">Bio</label>  
                                <textarea id="about" name="bio" rows="3"  class="shadow-none bg-gray-100">{{user_profile.bio}}</textarea>
                            </div>
                            <div class="col-span-2">
                                <label for=""> Location</label>
                                <input type="text" name="location" value="{{user_profile.location}}" rows="3" class="shadow-none bg-gray-100">
                            </div>
                            <!-- <div>
                               <label for=""> Working at</label>
                               <input type="text" placeholder="" class="shadow-none bg-gray-100">
                            </div>  -->
                            <!-- <div>
                               <label for=""> Relationship </label>
                               <select id="relationship" name="relationship"  class="shadow-none bg-gray-100">
                                <option value="0">None</option>
                                <option value="1">Single</option>
                                <option value="2">In a relationship</option>
                                <option value="3">Married</option>
                                <option value="4">Engaged</option>
                              </select>
                            </div> -->
                       </div> 
    
                       <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                           <button class="p-2 px-4 rounded bg-gray-50 text-red-500"> 
                               <a href="{% url 'core:index' %}">Cancel</a> </button>
                           <button type="submit" class="button bg-blue-700"> Save </button>
                       </div>
                    </form>
    
                    </div>

                    <!-- <div>
                        <h3 class="text-xl mb-2"> Privacy</h3>
                        <p> </p>
                    </div>
                    <div class="bg-white rounded-md lg:shadow-lg shadow lg:p-6 p-4 col-span-2">

                    <div class="space-y-3">
                        <div class="flex justify-between items-center">
                            <div>
                                <h4> Who can follow me ?</h4>
                                <div>  </div>
                            </div>
                            <div class="switches-list -mt-8 is-large">
                                <div class="switch-container">
                                    <label class="switch"><input type="checkbox"><span class="switch-button"></span> </label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="flex justify-between items-center">
                            <div>
                                <h4> Show my activities ?</h4>
                                <div>  </div>
                            </div>
                            <div class="switches-list -mt-8 is-large">
                                <div class="switch-container">
                                    <label class="switch"><input type="checkbox" checked><span class="switch-button"></span> </label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="flex justify-between items-center">
                            <div>
                                <h4> Search engines?</h4>
                                <div>  </div>
                            </div>
                            <div class="switches-list -mt-8 is-large">
                                <div class="switch-container">
                                    <label class="switch"><input type="checkbox"><span class="switch-button"></span> </label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="flex justify-between items-center">
                            <div>
                                <h4> Allow Commenting?</h4>
                                <div>  </div>
                            </div>
                            <div class="switches-list -mt-8 is-large">
                                <div class="switch-container">
                                    <label class="switch"><input type="checkbox"><span class="switch-button"></span> </label>
                                </div>
                            </div>
                        </div>
                    </div>
    
                    </div> -->
                    <br>

                </div>

            </div>
            
        </div>

    </div>


    

 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <!-- <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script> -->
</body>

</html>